(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
function qidFor(audio,index){const q=audio.closest('.q');const t=q?.querySelector('.qtitle')?.textContent||'';const m=t.match(/^\s*(\d{1,2})\s*[.\-:]/);return m?Number(m[1]):index+1}
async function fileFromAudio(audio,index){const qid=qidFor(audio,index);const r=await fetch(audio.src,{cache:'no-store'});if(!r.ok)throw new Error(`AUDIO_${qid}_${r.status}`);const blob=await r.blob();const type=blob.type||'audio/webm';const ext=type.includes('ogg')?'ogg':type.includes('wav')?'wav':(type.includes('mp4')||type.includes('m4a'))?'m4a':'webm';return new File([blob],`Vivace-Q${String(qid).padStart(2,'0')}.${ext}`,{type})}
function status(msg,bad=false){let s=$('#vivaceShareStatus');if(!s)return;s.textContent=msg;s.style.color=bad?'#9b2e21':'#68756f'}
async function shareOne(audio,index,btn){const old=btn.textContent;btn.disabled=true;btn.textContent='מכין…';try{const file=await fileFromAudio(audio,index);if(!navigator.share)throw new Error('NO_SHARE');await navigator.share({files:[file],title:`Vivace — שאלה ${qidFor(audio,index)}`,text:'הקלטת Vivace OS לתמלול ב-ChatGPT'});}catch(e){if(e?.name!=='AbortError')alert('לא ניתן לשתף את ההקלטה מהמכשיר הזה.')}finally{btn.disabled=false;btn.textContent=old}}
function addSingleButtons(){const audios=$$('audio[src]');audios.forEach((audio,i)=>{const box=audio.closest('.audio')||audio.parentElement;if(!box||box.querySelector('.vivace-single-share'))return;const b=document.createElement('button');b.type='button';b.className='btn vivace-single-share';b.style.marginTop='8px';b.textContent='שתף הקלטה ל-ChatGPT';b.onclick=()=>shareOne(audio,i,b);box.appendChild(b)})}
async function shareAll(btn){const audios=$$('audio[src]');if(!audios.length)return;const old=btn.textContent;btn.disabled=true;btn.textContent='מכין את ההקלטות…';status('מוריד את הקבצים המקוריים מהאחסון הפרטי…');try{const files=[];for(let i=0;i<audios.length;i++){status(`מכין הקלטה ${i+1} מתוך ${audios.length}…`);files.push(await fileFromAudio(audios[i],i))}if(navigator.share&&(!navigator.canShare||navigator.canShare({files}))){status('בחר ChatGPT בחלון השיתוף.');await navigator.share({files,title:'Vivace OS — הקלטות לתמלול',text:'הקלטות Vivace OS לתמלול ב-ChatGPT'});status('הקבצים מוכנים לשיתוף.');}else{addSingleButtons();status('המכשיר לא תומך בשיתוף כמה קבצים יחד. הוספתי כפתור שיתוף ליד כל הקלטה.',true)}}catch(e){console.error(e);addSingleButtons();status('שיתוף מרובה לא הצליח. אפשר לשתף כל הקלטה בנפרד מהכפתור שלידה.',true)}finally{btn.disabled=false;btn.textContent=old}}
function mount(){const audios=$$('audio[src]');if(!audios.length)return;addSingleButtons();if($('#vivaceShareToChatGPT'))return;const host=$('.back')?.parentElement||$('.card');if(!host)return;const wrap=document.createElement('div');wrap.id='vivaceShareWrap';wrap.className='card';wrap.style.border='1px solid #d6b36c';wrap.innerHTML=`<div class="row"><div><b>תמלול ב-ChatGPT</b><div class="muted">שולח את קבצי האודיו המקוריים — לא תמלול מהדפדפן.</div></div><button id="vivaceShareToChatGPT" class="btn" type="button">שתף את כל ההקלטות ל-ChatGPT</button></div><div id="vivaceShareStatus" class="muted" style="margin-top:8px"></div>`;host.insertAdjacentElement('afterend',wrap);$('#vivaceShareToChatGPT').onclick=()=>shareAll($('#vivaceShareToChatGPT'))}
const obs=new MutationObserver(()=>mount());obs.observe(document.documentElement,{childList:true,subtree:true});setTimeout(mount,300);setTimeout(mount,1200);
})();