(()=>{'use strict';
const AUDIO_DB='vivace-owner-discovery-audio-v1',AUDIO_STORE='recordings';
const PREVIEW_API='https://eadljasmuqnzcrfudsib.supabase.co/functions/v1/vivace-audio-preview';
const FORM_HEADER='owner-discovery-v1';
const APPROVED_KEY='vivace-approved-preview-transcripts-v1';
const SEEN=new Map();
let running=false;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const clean=v=>String(v||'').replace(/\s+/g,' ').trim();
function readApproved(){try{return JSON.parse(localStorage.getItem(APPROVED_KEY)||'{}')||{}}catch{return{}}}
function writeApproved(v){try{localStorage.setItem(APPROVED_KEY,JSON.stringify(v))}catch{}}
async function getRecordings(){return await new Promise(resolve=>{try{const req=indexedDB.open(AUDIO_DB,1);req.onerror=()=>resolve([]);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(AUDIO_STORE))req.result.createObjectStore(AUDIO_STORE,{keyPath:'questionId'})};req.onsuccess=()=>{const db=req.result;try{const tx=db.transaction(AUDIO_STORE,'readonly'),r=tx.objectStore(AUDIO_STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();resolve([])}}catch{db.close();resolve([])}}}catch{resolve([])}})}
async function sha256(blob){const bytes=await blob.arrayBuffer(),d=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function cardFor(qid){return document.querySelector(`[data-question-id="${qid}"]`)||document.querySelector(`#question-${qid}`)||$$('.interactive-question,[data-question-id]')[qid-1]||null}
function panel(qid){const card=cardFor(qid);if(!card)return null;let p=$(`.vivace-preview[data-qid="${qid}"]`,card);if(!p){p=document.createElement('div');p.className='vivace-preview';p.dataset.qid=String(qid);p.dir='rtl';p.style.cssText='margin-top:12px;padding:13px 14px;border:1px solid rgba(20,57,45,.18);border-radius:14px;background:#f8f5ee;color:#173027;font:14px/1.55 Arial,sans-serif;text-align:right';card.appendChild(p)}return p}
function setPanel(qid,html){const p=panel(qid);if(p)p.innerHTML=html}
function findRecordButton(qid){const card=cardFor(qid);if(!card)return null;return $$('button,[role="button"]',card).find(el=>/(הקלט|הקלטה|מיקרופון|record|microphone|\bmic\b)/i.test([clean(el.textContent),el.getAttribute('aria-label')||'',el.getAttribute('title')||'',String(el.className||''),el.dataset?.action||''].join(' ')))||null}
function invalidate(qid){const all=readApproved();if(all[qid]){delete all[qid];writeApproved(all)}}
async function requestPreview(rec,hash){const qid=Number(rec.questionId||0),blob=rec.blob;if(!qid||!blob)throw new Error('MISSING_AUDIO');const invite=sessionStorage.getItem('vivace-invite-token-v1')||'';if(!invite)throw new Error('INVITE_MISSING');const fd=new FormData();fd.append('audio',blob,`Q${String(qid).padStart(2,'0')}.webm`);fd.append('questionId',String(qid));fd.append('invite',invite);fd.append('sha256',hash);const r=await fetch(PREVIEW_API,{method:'POST',headers:{'x-vivace-form':FORM_HEADER},body:fd,cache:'no-store'});let data={};try{data=await r.json()}catch{}if(!r.ok||!data.ok){const e=new Error(data.error||`HTTP_${r.status}`);e.data=data;throw e}return data}
function escapeHtml(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function wireRerecord(qid){const p=panel(qid),b=$(`[data-vivace-rerecord="${qid}"]`,p);if(b)b.onclick=()=>{invalidate(qid);const recBtn=findRecordButton(qid);if(recBtn){recBtn.click();setPanel(qid,'<b>מקליט מחדש…</b> אחרי העצירה יופיע תמלול חדש כאן.')}else{setPanel(qid,'<b style="color:#8b2f25">לחץ שוב על כפתור ההקלטה של השאלה.</b>')}}}
function renderResult(qid,hash,data){const text=clean(data.transcript);if(data.status!=='ok'||!text){invalidate(qid);setPanel(qid,`<b style="color:#8b2f25">לא נשמע דיבור ברור.</b><div style="margin-top:5px">ההקלטה לא תישלח כתשובה. יש להקליט מחדש.</div><button type="button" data-vivace-rerecord="${qid}" style="margin-top:9px;border:0;border-radius:999px;padding:9px 14px;background:#8b2f25;color:#fff;font-weight:700">הקלט מחדש</button>`);wireRerecord(qid);return}
setPanel(qid,`<div style="font-size:12px;opacity:.7;margin-bottom:5px">זה מה ששמעתי:</div><div style="font-size:15px;font-weight:700">${escapeHtml(text)}</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button type="button" data-vivace-approve="${qid}" style="border:0;border-radius:999px;padding:9px 14px;background:#14392D;color:#fff;font-weight:700">נכון</button><button type="button" data-vivace-rerecord="${qid}" style="border:0;border-radius:999px;padding:9px 14px;background:#e6ded1;color:#173027;font-weight:700">הקלט מחדש</button></div>`);
const p=panel(qid),approve=$(`[data-vivace-approve="${qid}"]`,p);if(approve)approve.onclick=()=>{const all=readApproved();all[qid]={questionId:qid,text,source:clean(data.source||'gemini-preview'),audioSha256:hash,approvedAt:new Date().toISOString()};writeApproved(all);setPanel(qid,`<div style="font-size:12px;opacity:.7;margin-bottom:5px">תמלול מאושר ✓</div><div style="font-size:15px;font-weight:700">${escapeHtml(text)}</div><button type="button" data-vivace-rerecord="${qid}" style="margin-top:9px;border:0;border-radius:999px;padding:8px 12px;background:#e6ded1;color:#173027;font-weight:700">הקלט מחדש</button>`);wireRerecord(qid)};wireRerecord(qid)}
async function scan(){if(running)return;running=true;try{const recordings=await getRecordings(),approved=readApproved();for(const rec of recordings){const qid=Number(rec?.questionId||0),blob=rec?.blob;if(!qid||!blob)continue;let hash='';try{hash=await sha256(blob)}catch{continue}if(SEEN.get(qid)===hash)continue;SEEN.set(qid,hash);if(approved[qid]?.audioSha256===hash){setPanel(qid,`<div style="font-size:12px;opacity:.7;margin-bottom:5px">תמלול מאושר ✓</div><div style="font-size:15px;font-weight:700">${escapeHtml(clean(approved[qid].text))}</div><button type="button" data-vivace-rerecord="${qid}" style="margin-top:9px;border:0;border-radius:999px;padding:8px 12px;background:#e6ded1;color:#173027;font-weight:700">הקלט מחדש</button>`);wireRerecord(qid);continue}invalidate(qid);setPanel(qid,'<b>מתמלל את ההקלטה…</b>');try{const result=await requestPreview(rec,hash);renderResult(qid,hash,result)}catch(e){console.error('Vivace preview failed',e);setPanel(qid,'<b style="color:#8b2f25">לא הצלחנו לבדוק את ההקלטה.</b><div style="margin-top:5px">כדי למנוע תמלול שגוי, יש להקליט מחדש או לנסות שוב מאוחר יותר.</div>')}}}finally{running=false}}
window.__vivaceGetApprovedPreviewTranscripts=()=>readApproved();
setInterval(()=>void scan(),1200);setTimeout(()=>void scan(),500);
})();
